version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hyf-sns"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fh54iz3nan0g"
s3_prefix = "hyf-sns"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
