AWSTemplateFormatVersion: 2010-09-09
Description: >-
  hyf-sns-slackWebhook

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  SlackWebhookUrl:
    Type: String
  PersonsTable:
    Type: String

Resources:
  SimpleTopic:
    Type: AWS::SNS::Topic
  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SNS topic.
      Runtime: nodejs14.x
      Handler: src/handlers/sns-payload-logger.snsPayloadLoggerHandler
      Environment:
        Variables:
          SLACK_URL: !Ref SlackWebhookUrl
          PERSONS_TABLE: !Ref PersonsTable
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SimpleTopic
      MemorySize: 128
      Timeout: 100
      Policies:
        - AmazonDynamoDBFullAccess #Give DynamoDB Full Access to your Lambda Function
        - AWSLambdaBasicExecutionRole # Give Lambda basic execution Permission to the helloFromLambda
