AWSTemplateFormatVersion: 2010-09-09
Description: >-
  serverlessproject
  
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'*'"
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  getAllPersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllPersonsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
      Environment:
        Variables:
          personsTable: !Ref PersonsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref MyApi
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
      Environment:
        Variables:
          personsTable: !Ref PersonsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            RestApiId: !Ref MyApi
  putPersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putPersonsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Environment:
        Variables:
          personsTable: !Ref PersonsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
        - SNSPublishMessagePolicy:
            TopicName: sns-slack-handler-SimpleTopic-ZYHKZQJSSR3V
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref MyApi
  deleteByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-by-id.deleteByIdHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP delete method to delete one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
      Environment:
        Variables:
          personsTable: !Ref PersonsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE
            RestApiId: !Ref MyApi
  PersonsTable:
    Type: AWS::Serverless::SimpleTable
    Name: PersonsTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
