AWSTemplateFormatVersion: 2010-09-09
Description: >-
  serverlessproject
Transform:
Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'*'"

    Properties:
      StageName: Prod
  getAllPersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllPersonsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
      Environment:
        Variables:
          personsTable: !Ref PersonsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref MyApi
  putPersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putPersonsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref SampleTable
        SNSPublishMessagePolicy:
          TopicName: Alumni_Got_Employed
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref MyApi
  PersonsTable:
    Type: AWS::Serverless::SimpleTable
    Name: PersonsTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
